import type {
  AssessmentCard,
  AuditCertificate,
  ReasoningStep,
  RouteOption,
  Signal,
  SupplierNode,
  WorkflowState,
} from "@/types/workflow";

export type DemoStage = {
  stage: WorkflowState["stage"];
  title: string;
  agent: string;
  summary: string;
  outcome: string;
};

export type DemoPipelineStep = {
  id: string;
  order: number;
  title: string;
  agent: string;
  mode: "autonomous" | "human" | "execution";
  summary: string;
  outcome: string;
};

export const demoWorkflowState: WorkflowState = {
  workflow_id: "demo-hormuz-blockade-2026-07",
  stage: "AUDIT",
  status: "complete",
  created_at: "2026-07-06T02:17:00Z",
  updated_at: "2026-07-06T05:44:24Z",
};

export const demoSignals: Signal[] = [
  {
    signal_id: "sig-hormuz-irgc",
    title: "AIS dark-zone expansion and naval exclusion warning near Strait of Hormuz",
    event_type: "maritimeChokepoint",
    severity: 9.3,
    location: "Strait of Hormuz",
    lat: 26.5667,
    lng: 56.25,
    source: "AIS + GDELT",
    source_url: "https://www.gdeltproject.org/",
    source_type: "geopolitical",
    verified: true,
    corroborated_by: ["Sanctions registry", "Commodity price feed", "Port call anomaly model"],
    corroboration_count: 3,
    detected_at: "2026-07-06T02:17:00Z",
    relevance_score: 0.96,
  },
  {
    signal_id: "sig-brent-spike",
    title: "Brent prompt contract jumps 8.4% as Indian refiners seek spot cargoes",
    event_type: "commodityShock",
    severity: 8.6,
    location: "ICE Brent market",
    lat: 51.5072,
    lng: -0.1276,
    source: "Commodity price feed",
    source_url: "https://www.theice.com/products/219/Brent-Crude-Futures",
    source_type: "regional",
    verified: true,
    corroborated_by: ["GDELT", "Refinery procurement watchlist"],
    corroboration_count: 2,
    detected_at: "2026-07-06T02:18:00Z",
    relevance_score: 0.9,
  },
  {
    signal_id: "sig-red-sea-houthi",
    title: "Houthi escalation increases Red Sea war-risk premium and tanker diversions",
    event_type: "shippingSecurity",
    severity: 8.1,
    location: "Bab el-Mandeb / Red Sea",
    lat: 12.61,
    lng: 43.33,
    source: "Maritime security feed",
    source_url: "https://www.imo.org/",
    source_type: "government",
    verified: false,
    corroborated_by: ["AIS", "Insurance premium monitor"],
    corroboration_count: 2,
    detected_at: "2026-07-06T02:22:00Z",
    relevance_score: 0.84,
  },
];

export const demoSuppliers: SupplierNode[] = [
  {
    supplier_id: "prod-saudi-arab-light",
    name: "Saudi Aramco Arab Light",
    city: "Ras Tanura",
    country: "Saudi Arabia",
    tier: 1,
    transport_mode: "tanker",
    category: "Arab Light crude",
    node_role: "crude_producer",
    crude_grade: "light_sour",
    api_gravity: 33.0,
    sulfur_pct: 1.8,
    compatible_refineries: ["Jamnagar", "Paradip"],
    import_share_pct: 18,
    lat: 26.6436,
    lng: 50.1592,
    exposure_score: 95,
    exposure_label: "High Risk",
    risk_points: 5,
    is_backup: false,
  },
  {
    supplier_id: "prod-iraq-basrah-medium",
    name: "Basrah Medium Program",
    city: "Basra",
    country: "Iraq",
    tier: 1,
    transport_mode: "tanker",
    category: "Basrah Medium crude",
    node_role: "crude_producer",
    crude_grade: "medium_sour",
    api_gravity: 29.5,
    sulfur_pct: 2.9,
    compatible_refineries: ["Jamnagar", "Paradip"],
    import_share_pct: 21,
    lat: 30.5085,
    lng: 47.7835,
    exposure_score: 97,
    exposure_label: "High Risk",
    risk_points: 5,
    is_backup: false,
  },
  {
    supplier_id: "ref-jamnagar",
    name: "Jamnagar Refinery Complex",
    city: "Jamnagar",
    country: "India",
    tier: 2,
    transport_mode: "sea",
    category: "complex refinery",
    node_role: "refinery",
    refinery_profile: ["light_sour", "medium_sour", "heavy_sour"],
    throughput_mbd: 1.24,
    lat: 22.4707,
    lng: 70.0577,
    exposure_score: 88,
    exposure_label: "High Risk",
    risk_points: 5,
    is_backup: false,
  },
  {
    supplier_id: "ref-paradip",
    name: "Paradip Refinery",
    city: "Paradip",
    country: "India",
    tier: 2,
    transport_mode: "sea",
    category: "coastal public-sector refinery",
    node_role: "refinery",
    refinery_profile: ["medium_sour", "heavy_sour"],
    throughput_mbd: 0.3,
    lat: 20.3167,
    lng: 86.6167,
    exposure_score: 79,
    exposure_label: "High Risk",
    risk_points: 5,
    is_backup: false,
  },
  {
    supplier_id: "spr-visakhapatnam",
    name: "SPR Visakhapatnam Cavern",
    city: "Visakhapatnam",
    country: "India",
    tier: 3,
    transport_mode: "pipeline",
    category: "strategic petroleum reserve",
    node_role: "spr_terminal",
    throughput_mbd: 0.42,
    lat: 17.6868,
    lng: 83.2185,
    exposure_score: 42,
    exposure_label: "Medium Risk",
    risk_points: 3,
    is_backup: true,
  },
];

export const demoRoutes: RouteOption[] = [
  {
    mode: "tanker_vlcc",
    engine: "maritime_tanker",
    distance_km: 2150,
    transit_days: 7.8,
    cost_usd: 1420000,
    lane: "Strait of Hormuz direct",
    chokepoint: "Strait of Hormuz",
    capacity_mmbbl: 2,
    draft_m: 20.5,
    charter_rate_usd_day: 95000,
    selected: false,
    recommended: false,
    restrictions: ["Blocked by exclusion zone", "War-risk premium exceeds policy threshold"],
  },
  {
    mode: "tanker_suezmax",
    engine: "maritime_tanker",
    distance_km: 2390,
    transit_days: 9.4,
    cost_usd: 1195000,
    lane: "Hormuz controlled convoy",
    chokepoint: "Strait of Hormuz",
    capacity_mmbbl: 1,
    draft_m: 17,
    charter_rate_usd_day: 72000,
    selected: false,
    recommended: false,
    restrictions: ["Lower parcel size leaves 0.6 mbd uncovered", "Convoy slot uncertain"],
  },
  {
    mode: "tanker_vlcc",
    engine: "maritime_tanker",
    distance_km: 11280,
    transit_days: 22.2,
    cost_usd: 3840000,
    cost_local: 320640000,
    currency: "INR",
    lane: "Cape of Good Hope",
    chokepoint: "Red Sea avoided",
    capacity_mmbbl: 2,
    draft_m: 20.5,
    charter_rate_usd_day: 95000,
    selected: true,
    recommended: true,
    restrictions: ["Adds about 14 days", "Requires SPR bridge draw until arrival"],
  },
];

export const demoAssessment: AssessmentCard = {
  workflow_id: demoWorkflowState.workflow_id,
  affected_suppliers: demoSuppliers.filter((supplier) => !supplier.is_backup),
  exposure_usd: 612000000,
  exposure_local: 51102000000,
  exposure_currency: "INR",
  days_at_risk: 22,
  confidence: 0.89,
  analysis_summary:
    "Hormuz disruption removes a large share of Middle East crude flow. The system ranks Cape-routed VLCC cargoes, computes refinery-grade compatibility, and schedules SPR drawdown to bridge the 22-day replacement window.",
  inflation_risk: "HIGH",
  spr_cover_days: 9.5,
  domestic_fuel_price_delta_pct: 6.8,
  power_sector_stress: "HIGH",
  currency_risk_index: 74,
};

export const demoReasoningSteps: ReasoningStep[] = [
  {
    agent: "geopolitical_risk_agent",
    stage: "chokepoint_probability",
    detail:
      "AIS dark zones, naval warnings, and commodity-price shock were fused into a 0.96 Hormuz disruption probability for crude corridors feeding India.",
    status: "success",
    timestamp: "2026-07-06T02:17:00Z",
    timestamp_ms: 1783304220000,
    output: { corridor: "Strait of Hormuz", probability: 0.96, corroborated_by: 3 },
  },
  {
    agent: "graph_agent",
    stage: "crude_refinery_compatibility",
    detail:
      "The graph matched Arab Light and Basrah Medium API/sulfur properties against Jamnagar and Paradip refinery profiles before ranking replacement cargoes.",
    status: "success",
    timestamp: "2026-07-06T02:17:01Z",
    timestamp_ms: 1783304221000,
    output: { compatible_refineries: ["Jamnagar", "Paradip"], incompatible_cargoes_rejected: 4 },
  },
  {
    agent: "spr_optimization_agent",
    stage: "drawdown_control_loop",
    detail:
      "SPR inventory was scheduled against a 1.6 mbd supply gap, preserving refinery throughput while alternate VLCC cargoes move around the Cape.",
    status: "success",
    timestamp: "2026-07-06T02:17:02Z",
    timestamp_ms: 1783304222000,
    output: { starting_cover_days: 9.5, first_phase_draw_mbd: 1.15, exhaustion_day: null },
  },
  {
    agent: "routing_agent",
    stage: "tanker_route_generation",
    detail:
      "Air and land modes were excluded for crude. The agent compared VLCC, Suezmax, convoy availability, drafts, speeds, charter rates, and Cape diversion costs.",
    status: "success",
    timestamp: "2026-07-06T02:17:03Z",
    timestamp_ms: 1783304223000,
    output: { recommended_mode: "tanker_vlcc", lane: "Cape of Good Hope", added_days: 14 },
  },
  {
    agent: "economic_impact_agent",
    stage: "downstream_stress",
    detail:
      "The scenario model estimated a 6.8% domestic fuel price impulse and high power-sector stress from gas/coal substitution and refinery run-rate pressure.",
    status: "success",
    timestamp: "2026-07-06T02:17:04Z",
    timestamp_ms: 1783304224000,
    output: { fuel_price_delta_pct: 6.8, power_sector_stress: "HIGH" },
  },
  {
    agent: "decision_agent",
    stage: "policy_gate_package",
    detail:
      "Decision package recommends Cape-routed VLCC procurement, SPR bridge draw, and refinery run-rate allocation for human approval.",
    status: "success",
    timestamp: "2026-07-06T02:17:05Z",
    timestamp_ms: 1783304225000,
    output: { requires_human_gate: true, recommendation: "approve_cape_vlcc_and_spr_draw" },
  },
  {
    agent: "audit_agent",
    stage: "assumption_register",
    detail:
      "The audit record captures supply-gap, SPR-cover, tanker-rate, crude-grade, and refinery-throughput assumptions for judge-visible validation.",
    status: "success",
    timestamp: "2026-07-06T05:44:24Z",
    timestamp_ms: 1783316664000,
    output: { frameworks: ["Energy Security SOP", "Strategic Reserves Decision Memo"] },
  },
];

export const demoAuditCertificate: AuditCertificate = {
  workflow_id: demoWorkflowState.workflow_id,
  generated_at: "2026-07-06T05:44:24Z",
  response_time_seconds: 137,
  stages_completed: ["DETECT", "ASSESS", "DECIDE", "ACT", "AUDIT"],
  compliance_frameworks: ["Energy Security SOP", "Strategic Reserve Drawdown Memo", "Crude Procurement Playbook"],
  pdf_url: "/demo/audit/hormuz-blockade-certificate.pdf",
};

export const demoStages: DemoStage[] = [
  {
    stage: "DETECT",
    title: "Signal",
    agent: "geopolitical_risk_agent",
    summary: "Monitors AIS, sanctions, maritime-security alerts, and Brent price shocks.",
    outcome: "Hormuz disruption probability crossed the 0.9 action threshold.",
  },
  {
    stage: "ASSESS",
    title: "Assess",
    agent: "graph_agent + spr_optimization_agent",
    summary: "Scores crude producer/refinery exposure and computes SPR bridge schedules.",
    outcome: "1.6 mbd gap mapped to 9.5 days of reserve cover and refinery run-rate stress.",
  },
  {
    stage: "DECIDE",
    title: "Decide",
    agent: "routing_agent",
    summary: "Ranks VLCC and Suezmax procurement corridors with chokepoint constraints.",
    outcome: "Cape-routed VLCC is selected despite added time because direct Hormuz risk is unacceptable.",
  },
  {
    stage: "ACT",
    title: "Act",
    agent: "procurement_orchestrator",
    summary: "Packages cargo nomination, charter desk instruction, and SPR draw order.",
    outcome: "Operator receives a policy-ready approval bundle instead of a generic RFQ.",
  },
  {
    stage: "AUDIT",
    title: "Audit",
    agent: "audit_agent",
    summary: "Writes assumptions, constraints, and economic impact for review.",
    outcome: "Judges can inspect every input used by the scenario model.",
  },
];

export const demoPipelineSteps: DemoPipelineStep[] = [
  {
    id: "step-1",
    order: 1,
    title: "Geopolitical signal fusion",
    agent: "geopolitical_risk_agent",
    mode: "autonomous",
    summary: "Combines AIS anomalies, sanctions pressure, maritime advisories, and commodity price signals.",
    outcome: "Hormuz and Red Sea disruption scores are generated continuously.",
  },
  {
    id: "step-2",
    order: 2,
    title: "Energy graph scoring",
    agent: "graph_agent",
    mode: "autonomous",
    summary: "Propagates risk through crude producers, tanker lanes, SPR terminals, and Indian refineries.",
    outcome: "Saudi, Iraq, Jamnagar, and Paradip nodes cross action thresholds.",
  },
  {
    id: "step-3",
    order: 3,
    title: "Crude compatibility check",
    agent: "refinery_agent",
    mode: "autonomous",
    summary: "Filters alternatives by API gravity, sulfur profile, and refinery processing envelope.",
    outcome: "Incompatible sweet/light-only cargoes are rejected before route ranking.",
  },
  {
    id: "step-4",
    order: 4,
    title: "SPR optimization",
    agent: "spr_optimization_agent",
    mode: "autonomous",
    summary: "Runs a daily control loop over supply gap, refinery throughput, reserve inventory, and replenishment ETA.",
    outcome: "A reserve bridge schedule is produced for the Cape arrival window.",
  },
  {
    id: "step-5",
    order: 5,
    title: "Tanker route generation",
    agent: "routing_agent",
    mode: "autonomous",
    summary: "Compares VLCC/Suezmax classes, draft limits, charter rates, speeds, and chokepoint restrictions.",
    outcome: "Cape route is selected; air and land fallbacks are explicitly invalidated.",
  },
  {
    id: "step-6",
    order: 6,
    title: "Impact simulation",
    agent: "economic_impact_agent",
    mode: "autonomous",
    summary: "Projects domestic fuel price movement and power-sector coal/gas stress.",
    outcome: "Fuel-price impulse and power-sector stress are attached to the decision package.",
  },
  {
    id: "step-7",
    order: 7,
    title: "Policy package",
    agent: "decision_agent",
    mode: "human",
    summary: "Narrows the response to one approval: cargo reroute, SPR draw, and refinery allocation.",
    outcome: "Human review focuses on assumptions and authority, not rebuilding the analysis.",
  },
  {
    id: "step-8",
    order: 8,
    title: "Execution and audit",
    agent: "procurement_orchestrator + audit_agent",
    mode: "execution",
    summary: "Records the chosen route, draw schedule, and assumptions for post-crisis review.",
    outcome: "The workflow closes with an evidence trail suitable for a government or refinery war room.",
  },
];
